import { Injectable } from '@angular/core';
import * as DemoOneWorker from 'worker-loader!../../web-workers/worker-demo1/demo1.worker.bundle.js';
import * as ReportParser from 'worker-loader!../../web-workers/report-parser-worker/report-parser.worker.bundle.js';


@Injectable()
export class WebWorkerService {

  demoOneWorker: Worker = new DemoOneWorker();
  reportParser: Worker = new ReportParser();

  constructor() {

  }

/*
initialize{
    // Demo 1 worker
    this.demoOneWorker.onmessage = function ( event ) {
     /!* const data = event.data; // "This text was generated by template B"
      console.log('Web Worker ONE Response: ', data);*!/
    };

   /!* const that = this;

    setTimeout(function () {
      console.log('\n\nPosting message to web worker ONE');
      that.demoOneWorker.postMessage('Worker ONE Data');
    }, 1000);*!/

    // Demo 2 worker

/!*
    setTimeout(function () {
      console.log('\n\nPosting message to web worker TWO');
      that.demoTwoWorker.postMessage('Worker TWO Data');
    }, 2000);*!/
  }
*/

}
